"""
Static + localized content for Daily Dose of Me (English + Mexican Spanish).

DAILY_QUESTIONS / DAILY_QUESTIONS_ES: parallel arrays (same index = same question).
TRIVIA_CATEGORIES: canonical keys; CATEGORY_LABELS maps key -> {en, es}.
CHALLENGE_FALLBACKS / _ES: used if the AI generator is unavailable.
"""

DAILY_QUESTIONS = [
    "If we were a talking animal duo, what species would each of us be and what annoying thing would we say?",
    "What would be our ridiculous side-hustle, and what's our company slogan?",
    "If we were supervillains, what would our villain names be?",
    "What reality TV show would we absolutely dominate as a couple?",
    "If we swapped bodies for 24 hours, what's the first thing you'd do?",
    "What would our couple's Halloween costume be if we went super budget?",
    "If a zombie apocalypse started right now, which of us survives longer and why?",
    "If we could swap lives with any fictional couple, who would it be?",
    "What is a completely useless talent you're oddly proud of?",
    "If our relationship had a theme song, what would it be?",
    "Who is the little spoon and who is the big spoon in this house?",
    "If we got lost together on a road trip, which of us panics first?",
    "If you described me to a police sketch artist, what would you say?",
    "Who would win in a dance battle between the two of us?",
    "What is my most annoying habit that you secretly find cute?",
    "If our relationship was a sandwich, what kind of sandwich would we be?",
    "Who takes longer to get ready when we go out?",
    "If we were both cars, what kind of cars would we be?",
    "What do you think our pet (or future pet) actually thinks about us?",
    "Who is the bigger baby when they're sick?",
    "What's a song you secretly love but never admit to?",
    "What's your go-to 'I'm completely exhausted' fast-food order?",
    "What's a movie you can watch over and over but pretend to hate?",
    "What small inconvenience makes you unreasonably angry?",
    "What's your weirdest late-night food craving?",
    "What emoji do you overuse the most when texting me?",
    "Do you have a signature dad joke? Let's hear it.",
    "What's a food combination you love that everyone else thinks is gross?",
    "Sunrise or sunset for our perfect date?",
    "Sweet or savory breakfast in bed?",
    "Would you rather we travel by time machine or teleportation?",
    "Read minds for an hour or be invisible for a day?",
    "If we opened a themed restaurant, what would it serve and look like?",
    "If we had a massive house, what's the one useless room we absolutely must have?",
    "Would you rather stay in for every date night or go out for every date night?",
    "Would you rather do one hobby together for life or never repeat the same activity twice?",
    "Would you rather I be super romantic or super practical?",
    "Would you rather have a partner who gives great gifts or great compliments?",
    "Would you rather cook every night while I clean, or the other way around?",
    "Would you rather always feel understood or always feel appreciated?",
    "Would you rather have more money but less time together, or less money and more time together?",
    "Would you rather kiss in the rain or under the stars?",
    "Would you rather plan a surprise date for me or have one planned for you?",
    "Would you rather randomly get fresh flowers or your favorite snacks?",
    "Would you rather celebrate anniversaries with a big elaborate date or a small meaningful gift?",
    "Would you rather have a couples photoshoot or a custom painting of us?",
    "Would you rather get a flirty text every morning or a flirty call every night?",
    "What was your very first impression of me?",
    "What do you think is my sexiest feature?",
    "How do I make you feel when I look at you from across the room?",
    "What's something I do entirely unintentionally that you love?",
    "What's your favorite kind of casual touch from me?",
    "Describe your perfect, uninterrupted romantic day with me.",
    "How do you feel about public displays of affection with me?",
    "What's the most playful memory you have of us so far?",
    "What's a cheesy pickup line that would always make you blush or laugh?",
    "What's the most flattering compliment I've ever given you?",
    "What's your favorite scent on me?",
    "What's your favorite way for us to initiate a cozy night in?",
    "What's the funniest thing that's ever happened to the two of us?",
]

DAILY_QUESTIONS_ES = [
    "Si fuéramos un dúo de animales que hablan, ¿qué especie sería cada quien y qué cosa molesta diríamos?",
    "¿Cuál sería nuestro negocito ridículo y cuál sería nuestro eslogan?",
    "Si fuéramos supervillanos, ¿cuáles serían nuestros nombres de villanos?",
    "¿En qué reality show arrasaríamos como pareja?",
    "Si intercambiáramos cuerpos por 24 horas, ¿qué es lo primero que harías?",
    "¿Cuál sería nuestro disfraz de pareja si lo hiciéramos bien barato?",
    "Si empezara un apocalipsis zombie ahorita, ¿quién de los dos sobrevive más y por qué?",
    "Si pudiéramos cambiar de vida con cualquier pareja ficticia, ¿quiénes serían?",
    "¿Cuál es un talento completamente inútil del que estás raramente orgulloso/a?",
    "Si nuestra relación tuviera una canción, ¿cuál sería?",
    "¿Quién es la cucharita chica y quién la grande en esta casa?",
    "Si nos perdiéramos juntos en un viaje, ¿quién entra en pánico primero?",
    "Si me describieras a un dibujante de retratos, ¿qué dirías?",
    "¿Quién ganaría en una batalla de baile entre nosotros dos?",
    "¿Cuál es mi manía más molesta que en secreto te parece tierna?",
    "Si nuestra relación fuera una torta, ¿de qué sería?",
    "¿Quién tarda más en arreglarse cuando salimos?",
    "Si ambos fuéramos coches, ¿qué tipo de coches seríamos?",
    "¿Qué crees que piensa de nosotros nuestra mascota (o la futura)?",
    "¿Quién es más chillón/a cuando se enferma?",
    "¿Cuál es una canción que amas en secreto pero nunca admites?",
    "¿Cuál es tu pedido de comida rápida cuando estás muerto/a de cansancio?",
    "¿Qué película puedes ver una y otra vez pero finges que odias?",
    "¿Qué pequeña molestia te enoja sin razón?",
    "¿Cuál es tu antojo más raro de medianoche?",
    "¿Qué emoji usas de más cuando me escribes?",
    "¿Tienes un chiste de papá clásico? A ver, cuéntalo.",
    "¿Cuál es una combinación de comida que amas y a todos les da asco?",
    "¿Amanecer o atardecer para nuestra cita perfecta?",
    "¿Desayuno dulce o salado en la cama?",
    "¿Preferirías que viajáramos en máquina del tiempo o por teletransportación?",
    "¿Leer mentes por una hora o ser invisible por un día?",
    "Si abriéramos un restaurante temático, ¿qué serviría y cómo se vería?",
    "Si tuviéramos una casota, ¿cuál es el cuarto inútil que sí o sí tendríamos?",
    "¿Preferirías quedarnos en casa en cada cita o salir en cada cita?",
    "¿Preferirías un solo pasatiempo juntos de por vida o nunca repetir la misma actividad?",
    "¿Preferirías que yo fuera súper romántico/a o súper práctico/a?",
    "¿Preferirías una pareja que da buenos regalos o buenos cumplidos?",
    "¿Preferirías cocinar cada noche mientras yo lavo, o al revés?",
    "¿Preferirías sentirte siempre comprendido/a o siempre valorado/a?",
    "¿Preferirías más dinero pero menos tiempo juntos, o menos dinero y más tiempo juntos?",
    "¿Preferirías besarnos bajo la lluvia o bajo las estrellas?",
    "¿Preferirías planear una cita sorpresa para mí o que yo la planee para ti?",
    "¿Preferirías recibir flores frescas de sorpresa o tus botanas favoritas?",
    "¿Preferirías celebrar aniversarios con una cita elaborada o un regalo pequeño y significativo?",
    "¿Preferirías una sesión de fotos de pareja o una pintura personalizada de nosotros?",
    "¿Preferirías un mensaje coqueto cada mañana o una llamada coqueta cada noche?",
    "¿Cuál fue tu primera impresión de mí?",
    "¿Cuál crees que es mi rasgo más sexy?",
    "¿Cómo te hago sentir cuando te miro desde el otro lado del cuarto?",
    "¿Qué hago sin querer que te encanta?",
    "¿Cuál es tu tipo de caricia casual favorita de mi parte?",
    "Describe tu día romántico perfecto y sin interrupciones conmigo.",
    "¿Cómo te sientes con las muestras de cariño en público conmigo?",
    "¿Cuál es el recuerdo más juguetón que tienes de nosotros hasta ahora?",
    "¿Cuál es una frase cursi para ligar que siempre te haría sonrojar o reír?",
    "¿Cuál es el cumplido más bonito que te he dado?",
    "¿Cuál es tu aroma favorito en mí?",
    "¿Cuál es tu forma favorita de empezar una noche acogedora juntos?",
    "¿Qué es lo más chistoso que nos ha pasado a los dos?",
]

TRIVIA_CATEGORIES = [
    "General Knowledge",
    "Movies & TV",
    "Music",
    "Food & Drink",
    "Geography",
    "Science",
    "History",
    "Sports",
    "Animals",
    "Pop Culture",
]

CATEGORY_LABELS = {
    "General Knowledge": {"en": "General Knowledge", "es": "Cultura general"},
    "Movies & TV": {"en": "Movies & TV", "es": "Cine y TV"},
    "Music": {"en": "Music", "es": "Música"},
    "Food & Drink": {"en": "Food & Drink", "es": "Comida y bebida"},
    "Geography": {"en": "Geography", "es": "Geografía"},
    "Science": {"en": "Science", "es": "Ciencia"},
    "History": {"en": "History", "es": "Historia"},
    "Sports": {"en": "Sports", "es": "Deportes"},
    "Animals": {"en": "Animals", "es": "Animales"},
    "Pop Culture": {"en": "Pop Culture", "es": "Cultura pop"},
}

CHALLENGE_FALLBACKS = [
    "Hide a little love note somewhere your partner will only find it 2 days from now.",
    "Secretly pick out your partner's outfit for one day this week.",
    "Plan a surprise 20-minute 'date' at home (snacks + a song) and spring it on them.",
    "Leave a voice note or text at a random time just to say one thing you adore about them.",
    "Recreate the snack or drink from one of your early dates and surprise them with it.",
    "Do one chore your partner secretly hates, without saying a word about it.",
    "Take a candid photo of a sweet moment this week and add it to your memories.",
    "Give your partner an unprompted 30-second shoulder rub at the most random moment.",
    "Write down 3 tiny things they did this week that made you smile and read them aloud.",
    "Plan a surprise walk or drive to somewhere new, even if it's just around the block.",
]

CHALLENGE_FALLBACKS_ES = [
    "Esconde una notita de amor donde tu pareja la encuentre apenas en 2 días.",
    "En secreto, escoge el outfit de tu pareja para un día de esta semana.",
    "Planea una 'cita' sorpresa de 20 minutos en casa (botanas + una canción) y sorpréndele.",
    "Manda una nota de voz o mensaje a una hora random solo para decir algo que adoras de él/ella.",
    "Recrea la botana o bebida de una de sus primeras citas y sorpréndele.",
    "Haz una tarea de la casa que tu pareja odia, sin decir ni una palabra.",
    "Toma una foto espontánea de un momento bonito esta semana y agrégala a sus recuerdos.",
    "Dale a tu pareja un masaje de hombros de 30 segundos en el momento más random.",
    "Escribe 3 cositas que hizo esta semana que te sacaron una sonrisa y léeselas en voz alta.",
    "Planea una caminata o paseo sorpresa a un lugar nuevo, aunque sea a la vuelta de la esquina.",
]
